// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sciencific_Article.Infastructure.Data;

#nullable disable

namespace Sciencific_Article.Infastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720064852_AddPaperLanguage")]
    partial class AddPaperLanguage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "aal_level", new[] { "aal1", "aal2", "aal3" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "code_challenge_method", new[] { "s256", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_status", new[] { "unverified", "verified" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "factor_type", new[] { "totp", "webauthn", "phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_authorization_status", new[] { "pending", "approved", "denied", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_client_type", new[] { "public", "confidential" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_registration_type", new[] { "dynamic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "oauth_response_type", new[] { "code" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "one_time_token_type", new[] { "confirmation_token", "reauthentication_token", "recovery_token", "email_change_token_new", "email_change_token_current", "phone_change_token" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "action", new[] { "INSERT", "UPDATE", "DELETE", "TRUNCATE", "ERROR" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "realtime", "equality_op", new[] { "eq", "neq", "lt", "lte", "gt", "gte", "in" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage", "buckettype", new[] { "STANDARD", "ANALYTICS", "VECTOR" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pg_stat_statements");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "extensions", "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vault", "supabase_vault");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Author", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("author_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExternalAuthorId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_author_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("AuthorId")
                        .HasName("authors_pkey");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Bookmark", b =>
                {
                    b.Property<string>("BookmarkId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("bookmark_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaperId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("paper_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_id");

                    b.HasKey("BookmarkId")
                        .HasName("bookmarks_pkey");

                    b.HasIndex("PaperId");

                    b.HasIndex("UserId");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.FollowTopic", b =>
                {
                    b.Property<string>("FollowTopicId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("follow_topic_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KeywordId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("keyword_id");

                    b.Property<string>("TopicId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("topic_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_id");

                    b.HasKey("FollowTopicId")
                        .HasName("follow_topics_pkey");

                    b.HasIndex("KeywordId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("follow_topics", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Journal", b =>
                {
                    b.Property<string>("JournalId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("journal_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Issn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("issn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("publisher");

                    b.HasKey("JournalId")
                        .HasName("journals_pkey");

                    b.ToTable("journals", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Keyword", b =>
                {
                    b.Property<string>("KeywordId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("keyword_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("KeywordId")
                        .HasName("keywords_pkey");

                    b.HasIndex(new[] { "Name" }, "keywords_name_key")
                        .IsUnique();

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("notification_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Paper", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("paper_id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<int?>("CitationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("citation_count");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DocType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_type");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("doi");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<string>("JournalId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("journal_id");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("SourceApi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_api");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("PaperId")
                        .HasName("papers_pkey");

                    b.HasIndex("JournalId");

                    b.ToTable("papers", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PaperAuthor", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("paper_id");

                    b.Property<string>("AuthorId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("author_id");

                    b.HasKey("PaperId", "AuthorId")
                        .HasName("paper_authors_pkey");

                    b.HasIndex("AuthorId");

                    b.ToTable("paper_authors", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PaperKeyword", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("paper_id");

                    b.Property<string>("KeywordId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("keyword_id");

                    b.HasKey("PaperId", "KeywordId")
                        .HasName("paper_keywords_pkey");

                    b.HasIndex("KeywordId");

                    b.ToTable("paper_keywords", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PaperTopic", b =>
                {
                    b.Property<string>("PaperId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("paper_id");

                    b.Property<string>("TopicId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("topic_id");

                    b.HasKey("PaperId", "TopicId")
                        .HasName("paper_topics_pkey");

                    b.HasIndex("TopicId");

                    b.ToTable("paper_topics", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PublicationTrend", b =>
                {
                    b.Property<string>("TrendId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trend_id");

                    b.Property<double?>("CitationAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("citation_average");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("PublicationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("publication_count");

                    b.Property<string>("TopicId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("topic_id");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("TrendId")
                        .HasName("publication_trends_pkey");

                    b.HasIndex("TopicId");

                    b.ToTable("publication_trends", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Report", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("report_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("ReportType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_type");

                    b.Property<string>("TopicId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("topic_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_id");

                    b.HasKey("ReportId")
                        .HasName("reports_pkey");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.ResearchTopic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("topic_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<string>("Field")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("field");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OpenAlexId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("open_alex_id");

                    b.Property<string>("Subfield")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subfield");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("WorksCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("works_count");

                    b.HasKey("TopicId")
                        .HasName("research_topics_pkey");

                    b.HasIndex(new[] { "Name" }, "research_topics_name_key")
                        .IsUnique();

                    b.ToTable("research_topics", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.SyncLog", b =>
                {
                    b.Property<string>("SyncLogId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("sync_log_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("RecordsInserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("records_inserted");

                    b.Property<string>("SourceApi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_api");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SyncTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sync_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SyncLogId")
                        .HasName("sync_logs_pkey");

                    b.ToTable("sync_logs", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.Paper", "Paper")
                        .WithMany("Bookmarks")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("bookmarks_paper_id_fkey");

                    b.HasOne("Sciencific_Article.Domain.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("bookmarks_user_id_fkey");

                    b.Navigation("Paper");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.FollowTopic", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.Keyword", "Keyword")
                        .WithMany("FollowTopics")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("follow_topics_keyword_id_fkey");

                    b.HasOne("Sciencific_Article.Domain.Entities.ResearchTopic", "Topic")
                        .WithMany("FollowTopics")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("fk_flollow_topic");

                    b.HasOne("Sciencific_Article.Domain.Entities.User", "User")
                        .WithMany("FollowTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("follow_topics_user_id_fkey");

                    b.Navigation("Keyword");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Paper", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.Journal", "Journal")
                        .WithMany("Papers")
                        .HasForeignKey("JournalId")
                        .HasConstraintName("fk_paper_journal");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PaperAuthor", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("paper_authors_author_id_fkey");

                    b.HasOne("Sciencific_Article.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("paper_authors_paper_id_fkey");

                    b.Navigation("Author");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PaperKeyword", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("paper_keywords_keyword_id_fkey");

                    b.HasOne("Sciencific_Article.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("paper_keywords_paper_id_fkey");

                    b.Navigation("Keyword");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PaperTopic", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.Paper", null)
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("paper_topics_paper_id_fkey");

                    b.HasOne("Sciencific_Article.Domain.Entities.ResearchTopic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("paper_topics_topic_id_fkey");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.PublicationTrend", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.ResearchTopic", "Topic")
                        .WithMany("PublicationTrends")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("publication_trends_topic_id_fkey");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Report", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.ResearchTopic", "Topic")
                        .WithMany("Reports")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("fk_report_topic");

                    b.HasOne("Sciencific_Article.Domain.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("reports_user_id_fkey");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.User", b =>
                {
                    b.HasOne("Sciencific_Article.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_users_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Journal", b =>
                {
                    b.Navigation("Papers");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Keyword", b =>
                {
                    b.Navigation("FollowTopics");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Paper", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.ResearchTopic", b =>
                {
                    b.Navigation("FollowTopics");

                    b.Navigation("PublicationTrends");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sciencific_Article.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("FollowTopics");

                    b.Navigation("Notifications");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
