// GENERATED BY: flutterfire configure --project=scientific-article-b73bc
// If you have not yet run `flutterfire configure`, run it and replace this file.
// For now this is a working stub that allows the app to build without Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XcVeQqPEJHOPqlfMU4slB6zY1ODQUDk',
    appId: '1:740754340231:android:dfbbd4be7e606c32767b22',
    messagingSenderId: '740754340231',
    projectId: 'scientific-article-b73bc',
    authDomain: 'scientific-article-b73bc.firebaseapp.com',
    storageBucket: 'scientific-article-b73bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XcVeQqPEJHOPqlfMU4slB6zY1ODQUDk',
    appId: '1:740754340231:android:dfbbd4be7e606c32767b22',
    messagingSenderId: '740754340231',
    projectId: 'scientific-article-b73bc',
    storageBucket: 'scientific-article-b73bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9XcVeQqPEJHOPqlfMU4slB6zY1ODQUDk',
    appId: '1:740754340231:android:dfbbd4be7e606c32767b22',
    messagingSenderId: '740754340231',
    projectId: 'scientific-article-b73bc',
    storageBucket: 'scientific-article-b73bc.firebasestorage.app',
    iosBundleId: 'com.example.prm393lab2jta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9XcVeQqPEJHOPqlfMU4slB6zY1ODQUDk',
    appId: '1:740754340231:android:dfbbd4be7e606c32767b22',
    messagingSenderId: '740754340231',
    projectId: 'scientific-article-b73bc',
    storageBucket: 'scientific-article-b73bc.firebasestorage.app',
    iosBundleId: 'com.example.prm393lab2jta.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9XcVeQqPEJHOPqlfMU4slB6zY1ODQUDk',
    appId: '1:740754340231:android:dfbbd4be7e606c32767b22',
    messagingSenderId: '740754340231',
    projectId: 'scientific-article-b73bc',
    storageBucket: 'scientific-article-b73bc.firebasestorage.app',
  );
}
